language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - mkdir -p build/logs

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit -d memory_limit=1024M --coverage-clover=./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

